[package]
name = "pdf_diff"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
diff_img = { git = "https://github.com/chris-o-r/diff-img" }

pdfium = "0.9.5"
anyhow = "1.0.99"


[lib]
name = "lib"
path = "src/lib/mod.rs"
